name: Build binaries

on:
  push:
    branches: [ main ]
    paths:
      - "upload-to-server"

jobs:
  macos-build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Homebrew
      id: set-up-homebrew
      uses: Homebrew/actions/setup-homebrew@master
    - name: Set up ldid
      run: brew install ldid
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: make
    - name: Pack binaries
      run: |
        mv build/hashes.json build/hashes-1.json
        tar -czf fb-macos-binaries.tar.gz build/*
    - name: Load Key
      env:
        FBKEY: ${{ secrets.FBKEY }}
      run: |
        echo "$FBKEY">~/fbkey
        mkdir -p ~/.ssh
        printf "StrictHostKeyChecking no\nUserKnownHostsFile /dev/null">~/.ssh/config
        chmod 0600 ~/fbkey
    - name: Upload binaries
      run: |
        echo "put fb-macos-binaries.tar.gz">~/a
        sftp -i ~/fbkey -b ~/a root@fastbuilder.pro
        ssh -i ~/fbkey root@fastbuilder.pro "mkdir -p fbbinaries;mv fb-macos-binaries.tar.gz fbbinaries/"
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Set up NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r20b
        add-to-path: false
    - name: Move NDK
      run: mv ${{ steps.setup-ndk.outputs.ndk-path }} ${HOME}/android-ndk-r20b
    - name: Install mingw compiler
      run: sudo apt install gcc-mingw-w64-i686 gcc -y
    - name: Build
      run: make
    - name: Pack binaries
      run: |
        mv build/hashes.json build/hashes-2.json
        tar -czf fb-linux-binaries.tar.gz build/*
    - name: Load Key
      env:
        FBKEY: ${{ secrets.FBKEY }}
      run: |
        echo "$FBKEY">~/fbkey
        mkdir -p ~/.ssh
        printf "StrictHostKeyChecking no\nUserKnownHostsFile /dev/null">~/.ssh/config
        chmod 0600 ~/fbkey
    - name: Upload binaries
      run: |
        echo "put fb-linux-binaries.tar.gz">~/a
        sftp -i ~/fbkey -b ~/a root@fastbuilder.pro
        ssh -i ~/fbkey root@fastbuilder.pro "mkdir -p fbbinaries;mv fb-linux-binaries.tar.gz fbbinaries/;cd fbbinaries;tar -xzf *.tar.gz;rm *.tar.gz"




